In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\ARIO\Documents\22 ML project\Recommendation-System.ipynb\ml-100k\u.data")

In [3]:
df.head()

   196\t242\t3\t881250949
0  186\t302\t3\t891717742
1   22\t377\t1\t878887116
2   244\t51\t2\t880606923
3  166\t346\t1\t886397596
4  298\t474\t4\t884182806

In [5]:
df = pd.read_csv(r"C:\Users\ARIO\Documents\22 ML project\Recommendation-System.ipynb\ml-100k\u.data",
                 sep='\t',
                 header=None,
                 names=["user_id", "movie_id", "rating", "timestamp"])

In [6]:
df.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [7]:
df.isnull().sum()

user_id      0
movie_id     0
rating       0
timestamp    0
dtype: int64

            user_id       movie_id         rating     timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08

In [10]:
df["rating"].value_counts().sort_index()

rating
1     6110
2    11370
3    27145
4    34174
5    21201
Name: count, dtype: int64

In [11]:
df["user_id"].nunique()

943

In [12]:
df["movie_id"].nunique()

1682

In [13]:
movies = pd.read_csv(
    r"C:\Users\ARIO\Documents\22 ML project\Recommendation-System.ipynb\ml-100k\u.item",
    sep="|",
    encoding="latin-1",
    header=None
)

In [23]:
movies = movies.iloc[:, [0, 1]]
movies.columns = ["movie_id", "title"]

In [24]:
df = df.merge(movies, on="movie_id")

In [25]:
df.head()

,user_id,movie_id,rating,timestamp,title_x,title_y
0,196,242,3,881250949,Kolya (1996),Kolya (1996)
1,186,302,3,891717742,L.A. Confidential (1997),L.A. Confidential (1997)
2,22,377,1,878887116,Heavyweights (1994),Heavyweights (1994)
3,244,51,2,880606923,Legends of the Fall (1994),Legends of the Fall (1994)
4,166,346,1,886397596,Jackie Brown (1997),Jackie Brown (1997)

In [26]:
df.columns

Index(['user_id', 'movie_id', 'rating', 'timestamp', 'title_x', 'title_y'], dtype='object')

In [27]:
(df["title_x"] == df["title_y"]).all()

np.True_

In [28]:
df = df.drop(columns=["title_y"])
df = df.rename(columns={"title_x": "title"})

In [29]:
df.head()

   user_id  movie_id  rating  timestamp                       title
0      196       242       3  881250949                Kolya (1996)
1      186       302       3  891717742    L.A. Confidential (1997)
2       22       377       1  878887116         Heavyweights (1994)
3      244        51       2  880606923  Legends of the Fall (1994)
4      166       346       1  886397596         Jackie Brown (1997)

In [31]:
df.shape

(100000, 5)

In [32]:
user_movie_matrix = df.pivot_table(
    index="user_id",
    columns="title",
    values="rating"
)

In [33]:
user_movie_matrix.shape

(943, 1664)

In [34]:
user_movie_matrix.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

movie_similarity = cosine_similarity(user_movie_matrix.T)

ValueError: Input contains NaN.