# Movie Rating Prediction Using Regression

## Project Overview

This project uses the MovieLens 100K dataset to predict movie ratings based on user IDs and movie IDs.

A Linear Regression model is built using Scikit-learn. The user and movie IDs are converted into categorical features using One-Hot Encoding.

The model is evaluated using Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE). Its performance is also compared with a simple baseline model that predicts the average rating.

## Technologies Used
- Python
- Pandas
- NumPy
- Scikit-learn
- Jupyter Notebook

## Dataset
MovieLens 100K — a dataset containing 100,000 movie ratings from 943 users across 1,682 movies.

## Project Goals
- Prepare the dataset for machine learning.
- Build a regression model to predict movie ratings.
- Evaluate model performance.
- Compare the model with a baseline predictor.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\ARIO\Documents\22 ML project\Recommendation-System.ipynb\ml-100k\u.data")

In [3]:
df.head()

   196\t242\t3\t881250949
0  186\t302\t3\t891717742
1   22\t377\t1\t878887116
2   244\t51\t2\t880606923
3  166\t346\t1\t886397596
4  298\t474\t4\t884182806

In [4]:
df = pd.read_csv(r"C:\Users\ARIO\Documents\22 ML project\Recommendation-System.ipynb\ml-100k\u.data",
                 sep='\t',
                 header=None,
                 names=["user_id", "movie_id", "rating", "timestamp"])

In [5]:
df.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [6]:
df.isnull().sum()

user_id      0
movie_id     0
rating       0
timestamp    0
dtype: int64

In [7]:
df["rating"].value_counts().sort_index()

rating
1     6110
2    11370
3    27145
4    34174
5    21201
Name: count, dtype: int64

In [8]:
df["user_id"].nunique()

943

In [9]:
df["movie_id"].nunique()

1682

In [10]:
movies = pd.read_csv(
    r"C:\Users\ARIO\Documents\22 ML project\Recommendation-System.ipynb\ml-100k\u.item",
    sep="|",
    encoding="latin-1",
    header=None
)

In [11]:
movies = movies.iloc[:, [0, 1]]
movies.columns = ["movie_id", "title"]

In [12]:
df = df.merge(movies, on="movie_id")

In [13]:
df.head()

   user_id  movie_id  rating  timestamp                       title
0      196       242       3  881250949                Kolya (1996)
1      186       302       3  891717742    L.A. Confidential (1997)
2       22       377       1  878887116         Heavyweights (1994)
3      244        51       2  880606923  Legends of the Fall (1994)
4      166       346       1  886397596         Jackie Brown (1997)

In [14]:
df.columns

Index(['user_id', 'movie_id', 'rating', 'timestamp', 'title'], dtype='object')

In [17]:
df.shape

(100000, 5)

In [18]:
df.head()

   user_id  movie_id  rating  timestamp                       title
0      196       242       3  881250949                Kolya (1996)
1      186       302       3  891717742    L.A. Confidential (1997)
2       22       377       1  878887116         Heavyweights (1994)
3      244        51       2  880606923  Legends of the Fall (1994)
4      166       346       1  886397596         Jackie Brown (1997)

In [20]:
user_movie_matrix = df.pivot_table(
    index="user_id",
    columns="title",
    values="rating"
)

In [21]:
user_movie_matrix.shape

(943, 1664)

In [22]:
user_movie_matrix = user_movie_matrix.fillna(0)

In [23]:
user_movie_matrix.isna().sum().sum()

np.int64(0)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
movie_similarity = cosine_similarity(user_movie_matrix.T)

In [26]:
user_movie_matrix.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,2.0,5.0,0.0,0.0,3.0,4.0,0.0,0.0,...,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0,0.0

In [27]:
user_movie_matrix.shape

(943, 1664)

In [28]:
movie_similarity .shape

(1664, 1664)

In [32]:
movie_titles = user_movie_matrix.columns

In [33]:
movie_titles[:10]

Index([''Til There Was You (1997)', '1-900 (1994)', '101 Dalmatians (1996)',
       '12 Angry Men (1957)', '187 (1997)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '3 Ninjas: High Noon At Mega Mountain (1998)', '39 Steps, The (1935)'],
      dtype='object', name='title')

In [35]:
movie_titles.get_loc("Toy Story (1995)")

1523

In [36]:
movie_similarity[1523]

array([0.08124415, 0.00539651, 0.40938563, ..., 0.09445545, 0.11559502,
       0.02359153])

In [38]:
import numpy as np 
similar_movies = np.argsort(movie_similarity[1523])[::-1]

In [39]:
similar_movies[:10]

array([1523, 1398, 1234,  744, 1251,  987, 1633, 1394,  498,  780])

In [40]:
def recommend_movies(movie_name, n=10):
    movie_index = movie_titles.get_loc(movie_name)

    similarities = movie_similarity[movie_index]

    similar_movies = np.argsort(similarities)[::-1]

    similar_movies = similar_movies[similar_movies != movie_index]

    return movie_titles[similar_movies[:n]]

In [43]:
df[["user_id", "movie_id", "rating"]].isnull().sum()

user_id     0
movie_id    0
rating      0
dtype: int64

In [44]:
from sklearn.model_selection import train_test_split

X = df[["user_id", "movie_id"]]
y = df["rating"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [45]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ("categorical", OneHotEncoder(handle_unknown="ignore"),
         ["user_id", "movie_id"])
    ]
)

In [46]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regression", LinearRegression())
])

model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['user_id', 'movie_id'])])),
                ('regression', LinearRegression())])

In [47]:
from sklearn.metrics import mean_absolute_error, mean_squared_error


y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

MAE: 0.7424518171683828
RMSE: 0.9430963869907288

In [48]:
results = X_test.copy()

results["actual_rating"] = y_test
results["predicted_rating"] = y_pred

results.head(10)

       user_id  movie_id  actual_rating  predicted_rating
75721      877       381              4          3.687549
80184      815       602              3          3.784747
19864       94       431              4          3.698542
76699      416       875              2          3.185917
92991      500       182              2          3.872070
76434      259      1074              3          3.207108
84004      598       286              5          3.910387
80917      886       496              4          3.962371
60767      837        15              3          3.409802
50074      521       184              4          2.938864

In [49]:
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error

baseline = DummyRegressor(strategy="mean")
baseline.fit(X_train, y_train)

baseline_pred = baseline.predict(X_test)

baseline_mae = mean_absolute_error(y_test, baseline_pred)

print("Baseline MAE:", baseline_mae)
print("Regression MAE:", mae)

Baseline MAE: 0.9419550125
Regression MAE: 0.7424518171683828

# Conclusion

In this project, a Linear Regression model was developed to predict movie ratings using user and movie IDs.

One-Hot Encoding was used to represent these IDs as categorical features. The model was evaluated using MAE and RMSE and compared with a baseline model.

## Results

| Metric | Result |
|---|---:|
| Regression MAE | 0.7425 |
| Regression RMSE | 0.9431 |
| Baseline MAE | 0.9420 |

The Linear Regression model achieved a lower MAE than the baseline model, reducing the Mean Absolute Error by approximately 21.2%.

## Future Improvements
- Experiment with Ridge Regression.
- Explore collaborative filtering techniques.
- Compare additional recommendation algorithms.
- Improve rating prediction performance.